### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'nodeValue'

### ISSUE THREAD

**Issue by michelep** [yunuscadirci/CallStranger#1]
Slightly modified version of https://github.com/5kyc0d3r/upnpy used for base UPnP communication
Stranger Host: http://20.42.105.45
Stranger Port: 80
**Traceback (most recent call last):
  File "/CallStranger/upnpy/ssdp/SSDPDevice.py", line 158, in _get_services_request
    service_string = service.getElementsByTagName('serviceType')[0].firstChild.nodeValue**

_During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CallStranger.py", line 113, in <module>
    devices = upnp.discover()
  File "/CallStranger/upnpy/upnp/UPnP.py", line 33, in discover
    for device in self.ssdp.m_search(discover_delay=delay, st='upnp:rootdevice', **headers):
  File "/CallStranger/upnpy/ssdp/SSDPRequest.py", line 49, in m_search
    devices = self._send_request(self._get_raw_request())
  File "/CallStranger/upnpy/ssdp/SSDPRequest.py", line 100, in _send_request
    device = SSDPDevice(addr, response.decode())
  File "/CallStranger/upnpy/ssdp/SSDPDevice.py", line 86, in __init__
    self._get_services_request()
  File "/CallStranger/upnpy/ssdp/SSDPDevice.py", line 21, in wrapper
    return func(device, *args, **kwargs)
  File "/CallStranger/upnpy/ssdp/SSDPDevice.py", line 52, in wrapper
    return func(instance, *args, **kwargs)
  File "/CallStranger/upnpy/ssdp/SSDPDevice.py", line 176, in _get_services_request
    print('!Error in service definition',self.base_url,service_string)
UnboundLocalError: local variable 'service_string' referenced before assignment_

**Comment by yunuscadirci** [comment]
can you try again with latest version?

**Comment by hopeandnotexpect** [comment]
### Testing Results
Yes, that last update worked.  Thanks!

Git Commit ID: 5faa57f3429e75b2f8a291ac460f10bb258a993f

It looks like 2 types of devices are being flagged in my home under the "Verified vulnerable services" section.  Should this be added to your list of vulnerable devices?
* Linksys Velop Routers
* Bose SoundTouch 10 Speakers

### Background
UPNP is enabled on the router to allow chromecast etc. to work.  When I had read the Callstranger main website page, there were indications that only the UPNP endpoints exposed to the internet are vulnerable.

### Questions
- Does that imply that the router is ok since it is not an endpoint?
- Additionally, the Bose SoundTouch 10 speaker sits behind the router, so does that mean it is okay as well?

Bottomline:
I can't seem to determine whether or not I am exposed, and I seem to need UPNP enabled in order for Chromecast to work etc.  Help here is greatly appreciated!

### Testing Results Info
Below are the 2x devices that were flagged under the "Verified vulnerable services" section.

**Linksys Router**
> http://x.x.x.x:49152/upnp/event/Layer3Forwarding
http://x.x.x.x:49152/upnp/event/WANCommonInterfaceConfig0
http://x.x.x.x:49152/upnp/event/WANIPConnection0

**Bose SoundTouch 10**
> http://x.x.x.x:8091/AVTransport/Event
http://x.x.x.x:8091/ConnectionManager/Event
http://x.x.x.x:8091/RenderingControl/Event
http://x.x.x.x:8091/QPlay/Event

**Comment by yunuscadirci** [comment]
for home users, it is not problem until ports exposed to internet you can use online services to check open ports like https://www.ipfingerprints.com/portscan.php
